# The URL the site will be built for
base_url = "https://resinc-sust.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true

feed_filenames = ["rss.xml"]

author = "MD Gaziur Rahman Noor"

[markdown]
external_links_target_blank = true
bottom_footnotes = true
github_alerts = true
insert_anchor_links = "right"

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
style = "inline"
theme = "kanagawa-wave"

[extra]
# Put all your custom variables here
